/**
 * @File Name          : TestDemo.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 6/8/2019, 7:44:03 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    6/8/2019, 7:40:15 PM   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public class TestDemo{
    
    public static void demo(){
        System.debug('helloworld');
    }
}